# Generated by Django 3.1.7 on 2021-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210315_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='createdAt',
            field=models.DateField(default='2021-03-16'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-03-16'),
        ),
    ]
