# Generated by Django 3.1.7 on 2021-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210316_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='createdAt',
            field=models.DateField(default='2021-03-17'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-03-17'),
        ),
    ]
