# Generated by Django 3.1.7 on 2021-03-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210317_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='createdAt',
            field=models.DateField(default='2021-03-18'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-03-18'),
        ),
    ]
